Second/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/',include('myapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views

app_name ='myapp'

urlpatterns = [
    url(r'^login/$', views.login_user,name='login'),
    url(r'^logout/$', views.logout_user,name='logout'),
    url(r'^home/$', views.home,name='home'),
    url(r'^register/$', views.register,name='register'),
    url(r'^save/$', views.save,name='save'),
    url(r'^(?P<username>[\w-]+)/addproject/$', views.addproject,name='addproject'),
    url(r'^(?P<username>[\w-]+)/saveproject/$', views.saveproject,name='saveproject'),
    url(r'^(?P<username>[\w-]+)/profile/$', views.profile,name='profile'),
    url(r'^(?P<projectName>[\w-]+)/delete/$', views.deleteproject,name='deleteproject'),
    url(r'^(?P<projectName>[\w-]+)/description/$', views.description,name='description'),
    url(r'^(?P<projectName>[\w-]+)/(?P<username>[\w-]+)/addrequest/$', views.addrequest,name='addrequest'),
    url(r'^(?P<projectName>[\w-]+)/displaymembers/$', views.displaymembers,name='displaymembers'),
    url(r'^(?P<projectName>[\w-]+)/approverequests/$', views.approverequests,name='approverequests'),
    url(r'^(?P<projectName>[\w-]+)/(?P<username>[\w-]+)/addmembertoproject/$', views.addmembertoproject,name='addmembertoproject'),
    url(r'^myproject/$', views.myproject,name='myproject'),
    url(r'^(?P<projectName>[\w-]+)/creategroupchat/$', views.creategroupchat,name='creategroupchat'),
    url(r'^(?P<projectName>[\w-]+)/(?P<username>[\w-]+)/savechat/$', views.savechat,name='savechat'),
    url(r'^(?P<domain>[\w-]+)/search/$', views.searchresult,name='search'),







]

myapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
	name = models.CharField(max_length=100,default="ram")
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	profileImage=models.FileField(default='jon.jpg')
	age  = models.IntegerField(default =0)
	gender = models.CharField(max_length= 1, default='M')
	college = models.CharField(max_length=100 , default="NITW")
	branch = models.CharField(max_length=100,default="CSE")

class GroupDiscussion(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	projectName = models.CharField(max_length=100,default="")
	datetime = models.DateTimeField(auto_now_add = True)
	message = models.CharField(max_length=250)

class Project(models.Model):
	projectName = models.CharField(max_length=100)
	projectDescripton = models.CharField(max_length =500)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	mainCategory = models.CharField(max_length =50)
	subCategory = models.CharField(max_length=50)
	likes = models.IntegerField(default=0)	
	members = models.CharField(max_length=500,default="")
	requests = models.CharField(max_length=500,default="")
	# groupDiscussion = models.ForeignKey(GroupDiscussion,on_delete=models.CASCADE)
	date = models.DateField()



class UserChat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    senderUser = models.ForeignKey(User,related_name='messages_sent',on_delete=models.CASCADE)
    recieverUser = models.ForeignKey(User,related_name='messages_recieved',on_delete=models.CASCADE)
    message = models.CharField(max_length=200)

myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.template.context import RequestContext
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, redirect , get_object_or_404
from .models import UserProfile,Project,UserChat,GroupDiscussion
from django.contrib.auth.models import User
import datetime
from django.core.files.storage import FileSystemStorage
from django.utils import six
from django.contrib.auth.decorators import login_required 


# Create your views here.

def login_user(request):
		if not request.user.is_authenticated:
			print("hi")
			if request.method == "POST":
				username = request.POST['name']
				password = request.POST['password']
				user = authenticate(username=username , password=password)
				print(username)
				# print(password)
				login(request,user)
				if request.user.is_authenticated:
					return redirect('myapp:home')
				else:
					return render(request, 'myapp/login.html', {'error_message': 'Invalid login'})
			else:
				print("else")
				return render(request, 'myapp/login.html', {'error_message': 'Invalid login'})
		else:
			return redirect('myapp:home')

@login_required(login_url='myapp:login')
def home(request):
	context = {}
	context['username'] = request.user.username
	print("tired " +request.user.username)
	context['projects'] = Project.objects.all()
	return render(request,'myapp/index1.html',context)

def register(request):
	return render(request,'myapp/register.html')


def save(request):
	if request.method == "POST":
		name = request.POST['name']
		username = request.POST['username']
		password = request.POST['password']
		email = request.POST['email']
		image = request.FILES['image']
		gender = request.POST['gender']
		age = request.POST['age']
		college = request.POST['college']
		branch = request.POST['branch']
		user = User.objects.create_user(
			username = username,
			password = password,
			email=email
			)
		user.save()
		object1 = UserProfile(name = name , user=user ,profileImage = image,age =age,gender=gender,college=college,branch=branch)
		object1.save()
		return render(request,'myapp/login.html')

@login_required(login_url='myapp:login')
def addproject(request,username):
	print(request.user.username)
	return render(request,'myapp/addproject.html',{'username': username})

@login_required(login_url='myapp:login')
def saveproject(request,username):
	if request.method=="POST":
		print("Not")
		name = request.POST['name']
		description = request.POST['description']
		maincategory = request.POST['maincategory']
		subcategory = request.POST['subcategory']
		now = datetime.datetime.now()
		userr=request.user
		username=request.user.username
		print("username = "+ username)
		object1 = Project(projectName = name,projectDescripton = description,user=userr,mainCategory=maincategory,subCategory=subcategory,date=now,members=userr.username)
		object1.save()
		return redirect('myapp:home')
	else:
		return redirect('myapp:home')



def logout_user(request):
	logout(request)
	return redirect('myapp:login')

def profile(request,username):
	user =request.user
	context ={}
	context['projects'] = Project.objects.filter(user=user)
	context['userprofile'] = UserProfile.objects.get(user=user)
	return render(request,'myapp/profile.html',context)

def deleteproject(request,projectName):
	user =request.user
	object1=Project.objects.get(user=user,projectName=projectName)
	object1.delete()
	context ={}
	context['projects'] = Project.objects.filter(user=user)
	context['userprofile'] = UserProfile.objects.get(user=user)
	return render(request,'myapp/profile.html',context)

def description(request,projectName):
	context={}
	projects = Project.objects.filter(projectName=projectName)
	print("project "+str(len(projects)))
	owners = UserProfile.objects.get(user = projects[0].user)
	context['projects']=projects
	context['owners'] = owners
	return render(request,'myapp/description.html',context)



def displaymembers(request,projectName):
	context={}
	projects = Project.objects.filter(projectName=projectName)
	members = projects[0].members
	allmembers = members.split(';')
	print(allmembers)
	context['members']=allmembers
	context['projectName'] =projectName
	context['username']=request.user.username
	return render(request,'myapp/displaymembers.html',context)


def addrequest(request,projectName,username):
	projects = Project.objects.filter(projectName=projectName)
	check=0
	print(username)
	if projects[0].requests != "":
		allrequests = projects[0].requests.split(";")
		for i in (allrequests):
			print("Name = "+ i)
			if i ==username:
				check=1
				break;
		if check==1:
			return redirect('myapp:home')
		else:
			allmembers =projects[0].members.split(";") 
			for i in (allmembers):
				print("Name = "+ i)
				if i ==username:
					check=1
					break;
		if check==1:
			return redirect('myapp:home')
			requests = projects[0].requests+";"+username
	else:
		allmembers =projects[0].members.split(";") 
		for i in (allmembers):
			print("Name = "+ i)
			if i ==username:
				check=1
				break;
		if check==1:
			return redirect('myapp:home')
		requests=username
	members = projects[0].members
	projectName = projects[0].projectName
	projectDescripton = projects[0].projectDescripton
	subcategory = projects[0].subCategory
	maincategory = projects[0].mainCategory
	likes = projects[0].likes
	dates = projects[0].date
	user =projects[0].user
	projects[0].delete()
	newproject = Project(projectName=projectName,projectDescripton=projectDescripton,user=user,mainCategory=maincategory,subCategory=subcategory,likes=likes,members=members,requests=requests,date=dates)
	newproject.save()
	return redirect('myapp:home')

def approverequests(request,projectName):
	projects = Project.objects.filter(projectName=projectName)
	requests = projects[0].requests
	allrequest = requests.split(";")
	print(len(allrequest))
	print(allrequest)
	if allrequest[0] != "":
		context = {}
		context['allrequest']=allrequest
		context['project']=projectName
		return render(request,'myapp/approverequest.html',context)
	else:
		context ={}
		context['projects'] = Project.objects.filter(user=request.user)
		context['userprofile'] = UserProfile.objects.get(user=request.user)
		return render(request,'myapp/profile.html',context)





def addmembertoproject(request,projectName,username):
	projects = Project.objects.filter(projectName=projectName)
	members = projects[0].members+";"+username
	requests = projects[0].requests
	listofrequests = requests.split(";")
	print("len = " + str(len(listofrequests)))
	newrequests = ""
	for i in range(len(listofrequests)):
		if listofrequests[i] != username:
			print("Ans= "+ listofrequests[i])
			newrequests=newrequests+listofrequests[i]
	print("len = " + str(len(newrequests)))
	projectName = projects[0].projectName
	projectDescripton = projects[0].projectDescripton
	subcategory = projects[0].subCategory
	maincategory = projects[0].mainCategory
	likes = projects[0].likes
	dates = projects[0].date
	user =projects[0].user
	projects[0].delete()
	newproject = Project(projectName=projectName,projectDescripton=projectDescripton,user=user,mainCategory=maincategory,subCategory=subcategory,likes=likes,members=members,requests=newrequests,date=dates)
	newproject.save()
	projects = Project.objects.filter(projectName=projectName)
	requests = projects[0].requests
	allrequest = requests.split(";")
	context = {}
	context['allrequest']=allrequest
	context['project']=projectName
	context ={}
	context['projects'] = Project.objects.filter(user=request.user)
	context['userprofile'] = UserProfile.objects.get(user=request.user)
	return render(request,'myapp/profile.html',context)



def myproject(request):
	username = request.user.username
	ans =[]
	context={}
	projects = Project.objects.all()
	for i in range(len(projects)):
		allmembers =projects[i].members.split(";")
		for j in allmembers:
			if j== username:
				ans.append(projects[i])
				break;
	context['projects'] = ans
	return render(request,'myapp/myproject.html',context)


def creategroupchat(request,projectName):
	context={}
	projects = Project.objects.filter(projectName=projectName)
	members = projects[0].members
	allmembers = members.split(';')
	context['username'] =request.user.username
	context['allmembers'] = allmembers
	context['projectName'] = projectName
	chats  = GroupDiscussion.objects.filter(projectName=projectName).order_by('datetime')
	# orderedchats = chats.objects.order_by(datetime)
	context['chats']=chats
	print(chats)
	return render(request,'myapp/groupchat.html',context)


def savechat(request,projectName,username):
	context={}
	message = request.POST['message']
	object1 = GroupDiscussion(user=request.user,projectName= projectName,message=message,datetime=datetime.datetime.now())
	object1.save()
	context['username'] =request.user.username
	context['projectName'] = projectName
	chats  = GroupDiscussion.objects.filter(projectName=projectName).order_by('datetime')
	context['chats']=chats
	return render(request,'myapp/groupchat.html',context)


def searchresult(request,domain):
	context={}
	objects = Project.objects.filter(mainCategory=domain)
	context['projects']=objects
	context['username']=request.user.username
	return render(request,'myapp/index1.html',context)












	

myapp/templates/myapp/addproject.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Add Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Add Project</h2>
  <form action="{% url 'myapp:saveproject' username %}" enctype="multipart/form-data" method="POST" >
    <div class="form-group">
    {%csrf_token%}
      <label for="name">Name: </label>
      <input type="text" class="form-control" id="name" placeholder="Enter project name" name="name">
    </div>
    <div class="form-group">
      <label for="username"> Description: </label>
      <input type="text" class="form-control" id="description"  placeholder="Enter description" 
      name="description" style="height: 150px;>
    </div>
    <div class="form-group">
      <label for="username"> Main Category: </label>
      <input type="text" class="form-control" id="maincategory" placeholder="Enter main category" 
      name="maincategory">
    </div>
    <div class="form-group">
      <label for="username"> Sub Category: </label>
      <input type="text" class="form-control" id="subcategory" placeholder="Enter sub category" 
      name="subcategory">
    </div>



    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

</body>
</html>

myapp/templates/myapp/approverequest.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {%load static%}
  <title>Profile Page</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,400,300,500,700' rel='stylesheet' type='text/css'>

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href = "{% static 'myapp/style.css' %}">
</head>

<body>

	<div class = "my-container">
		<div class = "style_prevu_kit card-container">
				
				<div class = "card-details">
					ProjectName : &nbsp; {{project}}
				</div>				
		</div>
	</div>
	<div class="page-header" style="color:white;">
		<h2>
		List of Requests to be approved
		</h2>
	</div>
 	{% for i in allrequest %}
                <div class = "container">
                        <div class = "item_temp">
                               <a href="{% url 'myapp:addmembertoproject' project i  %}">
	  							<button>Approverequests {{i}}</button>
								 </a>		
                        </div>
                </div>
                {%endfor%}
</body>

</html>

myapp/templates/myapp/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  {%load static%}
  <title>Home Page</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="../../static/myapp/style.css">
</head>

<body>

	<div class="block-container">
		<div class = 'my-header'>
		Prinder 
		</div>
 	</div> 
 	
 	<div class='nav-div'>
 		<ul class="nav-bar">
 			<a href="#" class = "nav-list-link"><li class = "nav-list-item move-left">MyProjects</li></a>
 			<a href="{% url 'myapp:profile' username  %}" class = "nav-list-link"><li class = "nav-list-item move-left">Profile</li></a>
 			<a href="#" class = "nav-list-link"><li class = "nav-list-item move-left">Bookmarked</li></a>
 			<a href="{% url 'myapp:logout'  %}" class = "nav-list-link"><li class = "nav-list-item move-right">Logout</li></a>
 			<a href="{% url 'myapp:addproject' username %}" class = "nav-list-link"><li class = "nav-list-item move-right">Add Project</li></a>
 		</ul>
 	</div>

	<!-- <div class = "container">
		<form  action ="{% url 'BuyandSell: search'  data % }" role="search"  enctype="multipart/form-data">
			{% csrf_token %}
			<div class = "form-group">
				<label for="search_box" class = "label_class_1">Search</label>
				<input type="search_input" name= "data" class = "form-control" id="search_box" placeholder="Search">
				<button type="search" class = "btn btn-default">Search</button>
			</div>
		</form>
	</div>
 -->	

	<div class = "page-footer">
	</div>

	<div class="foot-div"></div>
{% block body %}
{% endblock %}
</body>

</html>

myapp/templates/myapp/index1.html
<!DOCTYPE html>
<html lang="en">

  <head>
  	{% load static %}
<style>
  div.col{
    color:white;
    text-align: center;
  }
</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="{ % static 'myapp/sidebar/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static 'myapp/sidebar/css/simple-sidebar.css'%}" rel="stylesheet">


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Prinder - Find your project partner</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'myapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'myapp/scrolling-nav.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="nav-list-link" href="{% url 'myapp:profile' username %}" style="text-decoration:none">PROFILE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li>
                <a href="#menu-toggle"  id="menu-toggle" style="text-decoration:none">DOMAINS  &nbsp</a>
        <!-- /#page-content-wrapper -->
            </li>

            <li class="nav-item">
              <a class="nav-list-link" href="{% url 'myapp:myproject'  %}" style="text-decoration:none"> MY PROJECTS &nbsp</a>
            </li>
            <li class="nav-item">
              <a class="nav-list-link" href="{% url 'myapp:addproject' username %}" style="text-decoration:none">&nbsp ADD PROJECT  &nbsp</a>
            </li>
            <li class="nav-item">
              <a class="nav-list-link" href="{% url 'myapp:logout'  %}" style="text-decoration:none">&nbsp LOG OUT </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!--Side Bar-->
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <a href="{% url 'myapp:search' "CSE" %}">COMPUTER SCIENCE</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "MECH" %}">MECHANICAL</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "EEE" %}">EEE</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "ECE" %}">ECE</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "BT" %}">BIOTECH</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "META" %}">METALLURGY</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "CHEM" %}">CHEMICAL</a>
                </li>
                <li>
                    <a href="{% url 'myapp:search'  "CE" %}">CIVIL</a>
                </li>
            </ul>
        </div>

         </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{%static 'myapp/sidebar/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{%static 'myapp/sidebar/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>PRINDER</h1>
        <p class="lead">A web portal to assist the students collaborate and make awesome projects.</p>
      </div>
    </header>

    {% for i in projects %}
    	<section id="dark"  class = "bg-dark">   	
	      <div class="container">
	        <div class="row">
	          <div class="col-lg-2 mx-auto">
	            <a style="text-decoration:none" href="{% url 'myapp:description' i.projectName %}">
	                <p> <h1> {{i.projectName}} </h1> </p>
	                </a>
	                	<div class="col">
	                    	  <h3 > {{i.mainCategory}} </h3>
	                    </div>
	                    <div class="col">
	                          <h3> {{i.subCategory}} </h3> 
	                    </div>      
	            </a>
	          </div>
	        </div>
	      </div>
	    </section>
	    <section id="light" >   	
	      <div class="container">
	        <div class="row">
	          <div class="col-lg-2 mx-auto">
	                  <a style="text-decoration:none" href="{% url 'myapp:displaymembers' i.projectName %}">
                    <div class="col">
	                  <p> <h3 class="col"> Members &nbsp </h3>

                      <a style="text-decoration:none" href="{% url 'myapp:addrequest' i.projectName username %}">
                      <h3 class="col"> Join </h3> </p>
                	  </a>
	            </a>
	          </div>
	        </div>
	      </div>
	    </section>
	    
    {% endfor %}

    
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'myapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'myapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{%static 'myapp/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{%static 'myapp/js/scrolling-nav.js' %}"></script>

  </body>

</html>

myapp/templates/myapp/profile.html
<!DOCTYPE html>
<html lang="en">

  <head>
  	{% load static %}
  	<style>
  	.myimg{
  		height: 200px;
  		width: 200px;
  		margin-bottom: 20px;
  	}
  	.col{
  		color:white;
  		text-align: center;
  	}
  	.heading{
  		color:#4286f4;
  		text-align: center;
  	}
  	div.mycard{
        color: white;
        text-align: center;
        padding: 10px 20px 10px 20px;
        margin-bottom: 20px;
        height: 50px;
      }
      div.bottom{
        color: white;
        text-align: center;
        padding: 10px 20px 10px 20px;
        height: 50px;
      }
  	</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Prinder - Find your project partner</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'myapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    	<link rel="stylesheet" href = "{% static 'myapp/style.css' %}">

    <link href="{% static 'myapp/scrolling-nav.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    

    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>PROFILE</h1>
       	<img src = "{{userprofile.profileImage.url}}" class ="myimg" />
				<div class = "mycard">
					{{userprofile.name}}
				</div>
				<div class = "mycard">
					{{userprofile.age}} YEARS
				</div>
				<div class = "bottom">
					{{userprofile.college}}
				</div>
    </header>

    {% for i in projects %}
    	<section id="dark"  class = "bg-dark">   	
	      <div class="container">
	        <div class="row">
	          <div class="col-lg-2 mx-auto">
	            <a style="text-decoration:none" href="{% url 'myapp:description' i.projectName %}">
	                <p> <h1 class="heading"> {{i.projectName}} </h1> </p>
	                </a>
	                	<div class="col">
	                    	  <h3> {{i.mainCategory}} </h3>
	                    </div>
	                    <div class="col">
	                          <h3> {{i.subCategory}} </h3> 
	                    </div>      
	            </a>
	          </div>
	        </div>
	      </div>
	    </section>
	    <section id="light" >   	
	      <div class="container">
	        <div class="row">
	          <div class="col-lg-2 mx-auto">
	                 <a href="{% url 'myapp:approverequests' i.projectName %}">
	  							<button>Approverequests</button>
								 </a>	
                               <a href="{% url 'myapp:deleteproject' i.projectName %}">
	  							<button>Delete</button>
					</a>		
	            </a>
	          </div>
	        </div>
	      </div>
	    </section>
	    
    {% endfor %}

    
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'myapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'myapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{%static 'myapp/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{%static 'myapp/js/scrolling-nav.js' %}"></script>

  </body>

</html>